package com.roomscanner.app.export;

import com.roomscanner.app.models.Point3D;
import com.roomscanner.app.models.RoomScan;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.List;

/**
 * Exports scan data to OBJ format (Wavefront OBJ)
 */
public class OBJExporter {
    
    /**
     * Export room scan to OBJ file
     * @param scan The room scan to export
     * @param outputFile The output file path
     * @return true if export successful, false otherwise
     */
    public static boolean exportToOBJ(RoomScan scan, File outputFile) {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(outputFile))) {
            // Write header
            writer.write("# OBJ file generated by Room Scanner\n");
            writer.write("# Scan: " + scan.getName() + "\n");
            writer.write("# Date: " + scan.getScanDate().toString() + "\n");
            writer.write("# Points: " + scan.getPointCount() + "\n\n");
            
            // Write vertices
            List<Point3D> points = scan.getPointCloud();
            for (Point3D point : points) {
                writer.write(String.format("v %.6f %.6f %.6f\n", 
                    point.getX(), point.getY(), point.getZ()));
            }
            
            // Write vertex colors (as comments, since basic OBJ doesn't support colors)
            writer.write("\n# Vertex colors (RGBA)\n");
            for (Point3D point : points) {
                int color = point.getColor();
                int r = (color >> 16) & 0xFF;
                int g = (color >> 8) & 0xFF;
                int b = color & 0xFF;
                int a = (color >> 24) & 0xFF;
                writer.write(String.format("# vc %d %d %d %d\n", r, g, b, a));
            }
            
            return true;
        } catch (IOException e) {
            e.printStackTrace();
            return false;
        }
    }
}
