package com.roomscanner.app.export;

import com.roomscanner.app.models.Point3D;
import com.roomscanner.app.models.RoomScan;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.List;

/**
 * Exports scan data to PLY format (Polygon File Format)
 */
public class PLYExporter {
    
    /**
     * Export room scan to PLY file
     * @param scan The room scan to export
     * @param outputFile The output file path
     * @return true if export successful, false otherwise
     */
    public static boolean exportToPLY(RoomScan scan, File outputFile) {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(outputFile))) {
            List<Point3D> points = scan.getPointCloud();
            int pointCount = points.size();
            
            // Write PLY header
            writer.write("ply\n");
            writer.write("format ascii 1.0\n");
            writer.write("comment Generated by Room Scanner\n");
            writer.write("comment Scan: " + scan.getName() + "\n");
            writer.write("comment Date: " + scan.getScanDate().toString() + "\n");
            writer.write("element vertex " + pointCount + "\n");
            writer.write("property float x\n");
            writer.write("property float y\n");
            writer.write("property float z\n");
            writer.write("property uchar red\n");
            writer.write("property uchar green\n");
            writer.write("property uchar blue\n");
            writer.write("property uchar alpha\n");
            writer.write("end_header\n");
            
            // Write vertex data with colors
            for (Point3D point : points) {
                int color = point.getColor();
                int r = (color >> 16) & 0xFF;
                int g = (color >> 8) & 0xFF;
                int b = color & 0xFF;
                int a = (color >> 24) & 0xFF;
                
                writer.write(String.format("%.6f %.6f %.6f %d %d %d %d\n",
                    point.getX(), point.getY(), point.getZ(), r, g, b, a));
            }
            
            return true;
        } catch (IOException e) {
            e.printStackTrace();
            return false;
        }
    }
}
